apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gamestore-user
  name: gamestore-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamestore-user
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gamestore-user
    spec:
      containers:
      - image: gamestore-user:0.0.1-SNAPSHOT
        name: gamestore-user
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            port: 9002
            path: /actuator/health/readiness
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: 9002
            path: /actuator/health/liveness
          initialDelaySeconds: 60
          periodSeconds: 10
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]
        resources: {}
        volumeMounts:
          - name: config-volume
            mountPath: /workspace/config
      volumes:
        - name: config-volume
          configMap:
            name: gamestore-config
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gamestore-user
  name: gamestore-user
spec:
  ports:
  - name: 9002-9002
    port: 9002
    protocol: TCP
    targetPort: 9002
  selector:
    app: gamestore-user
  type: ClusterIP
status:
  loadBalancer: {}
