apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gamestore-game.yaml
- gamestore-user.yaml
- gamestore-store.yaml
- gamestore-management.yaml
- mongo.yaml
- hpa.yaml

configMapGenerator:
  - name: gamestore-config
    files:
      - application.yaml